services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Shopware\Boilerplate\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'